// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incident.proto

package com.devproblems;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.devproblems.Empty)
    com.google.protobuf.MessageOrBuilder {
}
