// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incident.proto

package com.devproblems;

public interface IdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.devproblems.Id)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   */
  int getValue();
}
