// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incident.proto

package com.devproblems;

public final class IncidentOuterClass {
  private IncidentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devproblems_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devproblems_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devproblems_IncidentInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devproblems_IncidentInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devproblems_Id_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devproblems_Id_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devproblems_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devproblems_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devproblems_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devproblems_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devproblems_APIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devproblems_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016incident.proto\022\017com.devproblems\"\007\n\005Emp" +
      "ty\"N\n\014IncidentInfo\022\n\n\002id\030\001 \001(\005\022\r\n\005image\030" +
      "\002 \001(\t\022\023\n\013coordinates\030\003 \001(\t\022\016\n\006report\030\004 \001" +
      "(\t\"\023\n\002Id\022\r\n\005value\030\001 \001(\005\"\027\n\006Status\022\r\n\005val" +
      "ue\030\001 \001(\005\"2\n\014LoginRequest\022\020\n\010username\030\001 \001" +
      "(\t\022\020\n\010password\030\002 \001(\t\"<\n\013APIResponse\022\027\n\017r" +
      "esponseMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001" +
      "(\0052\200\003\n\010Incident\022G\n\014getIncidents\022\026.com.de" +
      "vproblems.Empty\032\035.com.devproblems.Incide" +
      "ntInfo0\001\022A\n\013getIncident\022\023.com.devproblem",
      "s.Id\032\035.com.devproblems.IncidentInfo\022N\n\016c" +
      "reateIncident\022\035.com.devproblems.Incident" +
      "Info\032\035.com.devproblems.IncidentInfo\022N\n\016u" +
      "pdateIncident\022\035.com.devproblems.Incident" +
      "Info\032\035.com.devproblems.IncidentInfo\022H\n\016d" +
      "eleteIncident\022\035.com.devproblems.Incident" +
      "Info\032\027.com.devproblems.Status2\214\001\n\004user\022D" +
      "\n\005login\022\035.com.devproblems.LoginRequest\032\034" +
      ".com.devproblems.APIResponse\022>\n\006logout\022\026" +
      ".com.devproblems.Empty\032\034.com.devproblems",
      ".APIResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_devproblems_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_devproblems_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devproblems_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_com_devproblems_IncidentInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_devproblems_IncidentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devproblems_IncidentInfo_descriptor,
        new java.lang.String[] { "Id", "Image", "Coordinates", "Report", });
    internal_static_com_devproblems_Id_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_devproblems_Id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devproblems_Id_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_com_devproblems_Status_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_devproblems_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devproblems_Status_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_com_devproblems_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_devproblems_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devproblems_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_com_devproblems_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_devproblems_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devproblems_APIResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
