// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incident.proto

package com.devproblems;

public interface IncidentInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.devproblems.IncidentInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string image = 2;</code>
   */
  java.lang.String getImage();
  /**
   * <code>string image = 2;</code>
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>string coordinates = 3;</code>
   */
  java.lang.String getCoordinates();
  /**
   * <code>string coordinates = 3;</code>
   */
  com.google.protobuf.ByteString
      getCoordinatesBytes();

  /**
   * <code>string report = 4;</code>
   */
  java.lang.String getReport();
  /**
   * <code>string report = 4;</code>
   */
  com.google.protobuf.ByteString
      getReportBytes();
}
